import {readFile,writeFile,stat} from 'node:fs/promises';
const read=p=>readFile(p,'utf8');
const [app,know,index,academy,academyJs,academyExtra,lawHtml,lawJs,lawApi,aiApi,quizApi,updatesApi]=await Promise.all([
'public/ndr-hr-v2/app.js','public/ndr-hr-v2/knowledge.js','public/ndr-hr-v2/index.html','public/ndr-hr-v2/academy.html','public/ndr-hr-v2/academy.js','public/ndr-hr-v2/academy-extra.js','public/ndr-hr-v2/law.html','public/ndr-hr-v2/law.js','api/ndr-hr-law.js','api/ndr-hr-ai.js','api/ndr-hr-quiz.js','api/ndr-hr-updates.js'].map(read));
let jsSyntax=true,lawSyntax=true,extraSyntax=true,errors=[];try{new Function(academyJs)}catch(e){jsSyntax=false;errors.push('academy syntax: '+e.message)}try{new Function(lawJs)}catch(e){lawSyntax=false;errors.push('law syntax: '+e.message)}try{new Function(academyExtra)}catch(e){extraSyntax=false;errors.push('academy extra syntax: '+e.message)}
const checks={
 academyLinked:index.includes('./academy.html'),lawLinked:index.includes('./law.html'),aiLinked:index.includes('./academy.html#ai'),legacyRedirect:(await read('public/ndr-hr-v2/knowledge.html')).includes('./academy.html'),
 old404Removed:!app.includes('/knowledge-centre/articles/64407')&&!know.includes('/knowledge-centre/articles/64407'),currentHRSD:app.includes('/decisions-and-regulations/regulation-and-procedures/%D9%86%D8%B8%D8%A7%D9%85-%D8%A7%D9%84%D8%B9%D9%85%D9%84'),
 academySyntax:jsSyntax,lawSyntax,extraSyntax,tracks14:(academyJs.match(/\{id:'(?:workforce|recruit|onboard|attendance|relations|payroll|performance|offboard|rewards|talent|gov|policy|experience|analytics)'/g)||[]).length===14,
 exam50:academy.includes('50 سؤال'),exam10Page:academy.includes('10 في كل صفحة'),examFivePages:academy.includes('الصفحة 1 من 5'),expandedBank:academyJs.includes('for(let k=1;k<=3;k++)'),freshQuiz:academyJs.includes("fetch('/api/ndr-hr-quiz'"),attemptHistory:academyJs.includes('ndrAcademyLastExam')&&academyJs.includes('ndrAcademyAttempts'),
 realCases:(academyJs.match(/laws\.moj\.gov\.sa/g)||[]).length>=4,caseLearning:academyJs.includes('ماذا يتعلم HR؟'),updatesView:academy.includes('view-updates')&&academyExtra.includes('/api/ndr-hr-updates'),internalLaw:lawHtml.includes('نظام العمل')&&lawJs.includes('/api/ndr-hr-law'),lawOfficial:lawApi.includes('laws.boe.gov.sa')&&lawApi.includes('hrsd.gov.sa'),lawFallback:lawApi.includes('verified-core-fallback')&&lawApi.includes('المادة 117'),
 aiAssistant:academy.includes('NDR HR INTELLIGENCE')&&academyJs.includes('/api/ndr-hr-ai'),aiGrounding:aiApi.includes('لا تخترع رقم مادة أو حكم')&&aiApi.includes('مخاطر شائعة'),aiFallback:aiApi.includes("mode:'fallback'"),quizGenerator:quizApi.includes('ai-refresh')&&quizApi.includes('daily-local'),updatesOfficial:updatesApi.includes('hrsd.gov.sa'),progress:academyJs.includes('localStorage')&&academyJs.includes('ndrAcademyProgress')
};
for(const p of ['public/ndr-hr-v2/academy.css','public/ndr-hr-v2/law.css'])try{const x=await stat(p);checks['file:'+p]=x.size>3000}catch{checks['file:'+p]=false}
const failed=Object.entries(checks).filter(([,v])=>!v).map(([k])=>k);const report={ok:!failed.length,generatedAt:new Date().toISOString(),checks,failed,metrics:{tracks:14,examQuestions:50,questionsPerPage:10,judicialCases:(academyJs.match(/laws\.moj\.gov\.sa/g)||[]).length,localQuestionVariants:'150+',laborLawMode:'official-live with verified fallback'}};await writeFile('public/ndr-hr-v2/academy-v3-audit.json',JSON.stringify(report,null,2),'utf8');console.log(`NDR HR Academy v3 gate: ${Object.keys(checks).length-failed.length}/${Object.keys(checks).length}; failures=${failed.length}`);if(failed.length)throw new Error('Academy v3 gate failed: '+failed.join(', ')+' '+errors.join('; '));