const defaults=[['مساعد مدرب كهرباء','دبلوم - كهرباء'],['مساعد مدرب كهرباء','دبلوم - كهرباء'],['مساعد مدرب ميكانيكا','دبلوم - ميكانيكا'],['مساعد مدرب ميكانيكا','دبلوم - ميكانيكا'],['مدرب حاسب آلي','حاسب آلي'],['مدرب لغة إنجليزية','لغة إنجليزية'],['مدرب رياضيات','رياضيات'],['مدرب سلاسل إمداد','سلاسل الإمداد'],['أخصائي تسويق','تسويق'],['أخصائي تسويق','تسويق']];
const stages=['بحث واستقطاب','فرز السير','مقابلات','Demo Class','عرض وظيفي','تم التغطية'];
const candidateStages=['جديد','تم التواصل','فرز أولي','مقابلة أولية','مقابلة فنية','Demo Class','مرشح نهائي','عرض وظيفي','احتياط','مرفوض'];
const gun=Gun({peers:['https://gun-manhattan.herokuapp.com/gun','https://gun-us.herokuapp.com/gun'],localStorage:true});
const root=gun.get('hipit-vacancies-v4').get('hipit-main-shared'),jobsRoot=root.get('dynamicJobs'),candRoot=root.get('candidates'),filesRoot=root.get('secureFilesV1');
let jobs={},candidates={},showOpen=false,editingId=null,seeded=false;
const LSKEY='ndr-recruitment-filekey-v1';
function b64u(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
function getKeyString(){const h=new URLSearchParams(location.hash.replace(/^#/,''));let k=h.get('k')||localStorage.getItem(LSKEY);if(!k){k=b64u(crypto.getRandomValues(new Uint8Array(32)));localStorage.setItem(LSKEY,k);h.set('k',k);history.replaceState(null,'',location.pathname+location.search+'#'+h.toString())}else{localStorage.setItem(LSKEY,k);if(!h.get('k')){h.set('k',k);history.replaceState(null,'',location.pathname+location.search+'#'+h.toString())}}return k}
const fileKeyString=getKeyString();
async function cryptoKey(){return crypto.subtle.importKey('raw',unb64u(fileKeyString),{name:'AES-GCM'},false,['encrypt','decrypt'])}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ids(){return Object.keys(jobs).filter(id=>jobs[id]&&!jobs[id].deleted).sort((a,b)=>(jobs[a].createdAt||0)-(jobs[b].createdAt||0))}
function candIds(jobId){return Object.keys(candidates[jobId]||{}).filter(id=>candidates[jobId][id]&&!candidates[jobId][id].deleted).sort((a,b)=>(candidates[jobId][a].createdAt||0)-(candidates[jobId][b].createdAt||0))}
function fileMeta(x,k){return x&&x[k+'FileId']?{id:x[k+'FileId'],name:x[k+'FileName']||'ملف',type:x[k+'FileType']||'application/octet-stream',chunks:Number(x[k+'FileChunks']||0)}:null}
function render(){const active=ids(),visible=active.filter(id=>!showOpen||!jobs[id].done),d=active.filter(id=>jobs[id].done).length;total.textContent=active.length;done.textContent=d;left.textContent=active.length-d;const p=active.length?Math.round(d/active.length*100):0;pct.textContent=p+'%';bar.style.width=p+'%';grid.innerHTML='';if(!visible.length){grid.innerHTML='<div class="empty">'+(active.length?'لا توجد شواغر متبقية حاليا ✓':'لا توجد شواغر')+'</div>';return}visible.forEach(id=>{const j=jobs[id],cids=candIds(id),c=document.createElement('div');c.className='card'+(j.done?' done':'');c.innerHTML=`<div class="head"><div class="check ${j.done?'done':''}">${j.done?'✓':''}</div><div class="headtext"><div class="title">${esc(j.title)}</div><div class="sub">${esc(j.track||'بدون تخصص محدد')} · شاغر ${String(active.indexOf(id)+1).padStart(2,'0')}</div></div><div class="actions"><button class="iconbtn edit">✎</button><button class="iconbtn delete">×</button></div></div><div class="row"><input class="selectedCandidate" placeholder="المرشح المختار" value="${esc(j.name)}"><select class="stage">${stages.map(s=>`<option ${j.stage===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="doneTag">تمت تغطية الشاغر ✓</div><div class="candidates"><div class="candHead"><b>المرشحون تحت المتابعة (${cids.length})</b><button class="btn candAdd">+ إضافة مرشح</button></div><div class="candList">${cids.map(cid=>candidateHtml(id,cid)).join('')}</div></div>`;
 c.querySelector('.check').onclick=()=>{const cur=jobs[id],nd=!cur.done;updateJob(id,{done:nd,stage:nd?'تم التغطية':(cur.stage==='تم التغطية'?'بحث واستقطاب':cur.stage)})};c.querySelector('.selectedCandidate').onchange=e=>updateJob(id,{name:e.target.value});c.querySelector('.stage').onchange=e=>updateJob(id,{stage:e.target.value,done:e.target.value==='تم التغطية'});c.querySelector('.edit').onclick=()=>openEdit(id);c.querySelector('.delete').onclick=()=>deleteJob(id);c.querySelector('.candAdd').onclick=()=>addCandidate(id);bindCandidates(c,id);grid.appendChild(c)})}
function candidateHtml(jobId,cid){const x=candidates[jobId][cid],cv=fileMeta(x,'cv'),app=fileMeta(x,'app');return `<div class="candItem" data-cid="${cid}"><div class="candTop"><input class="candName" placeholder="اسم المرشح" value="${esc(x.name)}"><select class="candStage">${candidateStages.map(s=>`<option ${x.stage===s?'selected':''}>${s}</option>`).join('')}</select><button class="iconbtn delete candDelete">×</button></div><div class="candExtra"><div><div class="fileBox"><label class="btn smallBtn filePick">📎 السيرة الذاتية<input class="cvInput" type="file" accept=".pdf,.doc,.docx"></label>${cv?`<button class="btn smallBtn cvOpen">فتح</button><span class="fileName">${esc(cv.name)}</span>`:`<span class="fileName">لا يوجد ملف</span>`}</div></div><div><div class="fileBox"><label class="btn smallBtn filePick">📎 طلب التوظيف<input class="appInput" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png"></label>${app?`<button class="btn smallBtn appOpen">فتح</button><span class="fileName">${esc(app.name)}</span>`:`<span class="fileName">لا يوجد ملف</span>`}</div></div></div><textarea class="notes" placeholder="ملاحظات المتابعة / آخر تحديث">${esc(x.notes||'')}</textarea></div>`}
function bindCandidates(card,jobId){card.querySelectorAll('.candItem').forEach(el=>{const cid=el.dataset.cid;el.querySelector('.candName').onchange=e=>updateCandidate(jobId,cid,{name:e.target.value});el.querySelector('.candStage').onchange=e=>updateCandidate(jobId,cid,{stage:e.target.value});el.querySelector('.candDelete').onclick=()=>deleteCandidate(jobId,cid);el.querySelector('.notes').onchange=e=>updateCandidate(jobId,cid,{notes:e.target.value});el.querySelector('.cvInput').onchange=e=>e.target.files[0]&&uploadCandidateFile(jobId,cid,'cv',e.target.files[0]);el.querySelector('.appInput').onchange=e=>e.target.files[0]&&uploadCandidateFile(jobId,cid,'app',e.target.files[0]);const cvb=el.querySelector('.cvOpen'),ab=el.querySelector('.appOpen');if(cvb)cvb.onclick=()=>openCandidateFile(jobId,cid,'cv');if(ab)ab.onclick=()=>openCandidateFile(jobId,cid,'app')})}
function updateJob(id,patch){const next={...jobs[id],...patch,updatedAt:Date.now()};jobs[id]=next;render();jobsRoot.get(id).put(next);toast('تم الحفظ')}
function newId(prefix='j'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function addJobs(title,track,qty){for(let i=0;i<qty;i++){const id=newId('j')+'_'+i,data={title,track,done:false,name:'',stage:'بحث واستقطاب',createdAt:Date.now()+i,updatedAt:Date.now()};jobs[id]=data;jobsRoot.get(id).put(data)}render();toast(qty>1?`تمت إضافة ${qty} شواغر`:'تمت إضافة الشاغر')}
function deleteJob(id){if(confirm('حذف هذا الشاغر من القائمة؟'))updateJob(id,{deleted:true})}
function addCandidate(jobId){const id=newId('c'),data={name:'',stage:'جديد',notes:'',createdAt:Date.now(),updatedAt:Date.now()};(candidates[jobId]||(candidates[jobId]={}))[id]=data;candRoot.get(jobId).get(id).put(data);render()}
function updateCandidate(jobId,cid,patch){const next={...(candidates[jobId]||{})[cid],...patch,updatedAt:Date.now()};candidates[jobId][cid]=next;candRoot.get(jobId).get(cid).put(next);render();toast('تم الحفظ')}
function deleteCandidate(jobId,cid){if(confirm('حذف المرشح من المتابعة؟'))updateCandidate(jobId,cid,{deleted:true})}
async function uploadCandidateFile(jobId,cid,kind,file){if(file.size>4*1024*1024){toast('حجم الملف كبير. الحد الحالي 4 MB');return}toast('جاري حفظ الملف...');try{const key=await cryptoKey(),iv=crypto.getRandomValues(new Uint8Array(12)),buf=await file.arrayBuffer(),enc=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,buf)),all=new Uint8Array(iv.length+enc.length);all.set(iv,0);all.set(enc,iv.length);let binary='';for(let i=0;i<all.length;i+=0x8000)binary+=String.fromCharCode(...all.subarray(i,i+0x8000));const b64=btoa(binary),chunkSize=28000,chunks=[];for(let i=0;i<b64.length;i+=chunkSize)chunks.push(b64.slice(i,i+chunkSize));const fid=newId('f'),node=filesRoot.get(jobId).get(cid).get(kind).get(fid);chunks.forEach((ch,i)=>node.get('c'+i).put({d:ch}));node.get('meta').put({name:file.name,type:file.type||'application/octet-stream',chunks:chunks.length,createdAt:Date.now()});const patch={};patch[kind+'FileId']=fid;patch[kind+'FileName']=file.name;patch[kind+'FileType']=file.type||'application/octet-stream';patch[kind+'FileChunks']=chunks.length;updateCandidate(jobId,cid,patch);toast('تم حفظ الملف')}catch(e){console.error(e);toast('تعذر حفظ الملف') }}
function onceData(node){return new Promise(r=>node.once(d=>r(d)))}
async function openCandidateFile(jobId,cid,kind){const x=candidates[jobId][cid],m=fileMeta(x,kind);if(!m)return;toast('جاري فتح الملف...');try{let b64='';const base=filesRoot.get(jobId).get(cid).get(kind).get(m.id);for(let i=0;i<m.chunks;i++){const o=await onceData(base.get('c'+i));if(!o||!o.d)throw new Error('missing chunk');b64+=o.d}const raw=atob(b64),all=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)all[i]=raw.charCodeAt(i);const iv=all.slice(0,12),cipher=all.slice(12),key=await cryptoKey(),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher),blob=new Blob([plain],{type:m.type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=m.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('تم فتح الملف')}catch(e){console.error(e);toast('تعذر فتح الملف من هذا الرابط') }}
const mb=modalBack,titleInput=jobTitle,trackInput=jobTrack,qtyInput=jobQty;function openAdd(){editingId=null;modalTitle.textContent='إضافة شاغر';titleInput.value='';trackInput.value='';qtyInput.value=1;qtyWrap.style.display='block';mb.classList.add('show');setTimeout(()=>titleInput.focus(),50)}function openEdit(id){editingId=id;modalTitle.textContent='تعديل الشاغر';titleInput.value=jobs[id].title||'';trackInput.value=jobs[id].track||'';qtyWrap.style.display='none';mb.classList.add('show')}function closeModal(){mb.classList.remove('show')}
addJob.onclick=openAdd;cancelJob.onclick=closeModal;mb.onclick=e=>{if(e.target===mb)closeModal()};saveJob.onclick=()=>{const t=titleInput.value.trim(),tr=trackInput.value.trim();if(!t){toast('اكتب المسمى الوظيفي');return}if(editingId){updateJob(editingId,{title:t,track:tr});closeModal();return}addJobs(t,tr,Math.max(1,Math.min(20,parseInt(qtyInput.value||'1',10))));closeModal()};filter.onclick=()=>{showOpen=!showOpen;filter.textContent=showOpen?'عرض الكل':'عرض المتبقي فقط';render()};copy.onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('تم نسخ رابط المشاركة')}catch(e){toast('انسخ رابط الصفحة من المتصفح')}};
jobsRoot.map().on((data,id)=>{if(!data)return;const local=jobs[id];if(local&&Number(data.updatedAt||0)<Number(local.updatedAt||0))return;jobs[id]=data;render();dot.classList.add('on');syncText.textContent='متصل'});candRoot.map().on((jobNode,jobId)=>{if(!jobNode)return;candRoot.get(jobId).map().on((data,cid)=>{if(!data)return;(candidates[jobId]||(candidates[jobId]={}));const local=candidates[jobId][cid];if(local&&Number(data.updatedAt||0)<Number(local.updatedAt||0))return;candidates[jobId][cid]=data;render()})});
setTimeout(()=>{if(ids().length===0&&!seeded){seeded=true;defaults.forEach((d,i)=>{const id='seed_'+String(i+1).padStart(2,'0'),data={title:d[0],track:d[1],done:false,name:'',stage:'بحث واستقطاب',createdAt:1000+i,updatedAt:Date.now()};jobs[id]=data;jobsRoot.get(id).put(data)});render()}dot.classList.add('on');syncText.textContent='متصل'},1800);render();