import {GoogleGenAI} from '@google/genai';
const RULES=[
['المادة 10','المدد والمواعيد في النظام تحسب هجريا ما لم ينص عقد العمل أو لائحة تنظيم العمل على خلاف ذلك.'],['المادة 53','فترة التجربة يجب النص عليها صراحة ولا يزيد مجموعها على 180 يوما مع مراعاة الأحكام الخاصة بالتكرار والأيام المستبعدة.'],['المادة 69','هناك مدد نظامية لإجراءات المخالفة والتحقيق وتوقيع الجزاء.'],['المادة 70','الغرامة عن المخالفة الواحدة لا تزيد على أجر خمسة أيام وتوجد ضوابط لمجموع التنفيذ.'],['المادة 75','في العقد غير المحدد والأجر الشهري: إشعار العامل 30 يوما إذا أنهى هو، و60 يوما إذا أنهى صاحب العمل.'],['المادة 76','عدم مراعاة الإشعار يرتب بدل المهلة أو المتبقي منها ما لم يوجد اتفاق أفضل.'],['المادة 77','تعويض الإنهاء غير المشروع يختلف بحسب نوع العقد عند عدم وجود تعويض تعاقدي محدد.'],['المادة 79 مكرر','الاستقالة تعد مقبولة بعد 30 يوما دون رد، مع إمكان تأجيل القبول حتى 60 يوما وفق شروط مكتوبة.'],['المادة 80','الفصل دون مكافأة أو إشعار حالات استثنائية لها شروط إثبات وإجراء، ويجب تمكين العامل من إبداء أسباب معارضته.'],['المادة 81','للعامل ترك العمل دون إشعار مع احتفاظه بحقوقه في الحالات المحددة نظاما.'],['المادة 84','المكافأة: نصف شهر عن كل سنة من أول خمس سنوات وشهر عن كل سنة تالية، والأجزاء بنسبة مدتها.'],['المادة 85','استحقاق المكافأة عند الاستقالة يتدرج بحسب مدة الخدمة ضمن نطاق المادة.'],['المادة 88','تصفية الحقوق خلال أسبوع إذا أنهى صاحب العمل، وحتى أسبوعين إذا أنهى العامل.'],['المادة 98','الحد العام 8 ساعات يوميا أو 48 أسبوعيا، ورمضان للمسلمين 6 يوميا أو 36 أسبوعيا.'],['المادة 107','الإضافي = ساعة من الأجر الفعلي + 50% من ساعة الأجر الأساسي.'],['المادة 109','الإجازة السنوية 21 يوما على الأقل وتصبح 30 بعد خمس سنوات متصلة.'],['المادة 117','المرضية: 30 كامل + 60 ثلاثة أرباع + 30 دون أجر خلال السنة المرضية.'],['GOSI','حد أجر الاشتراك الأعلى 45,000 ريال؛ والحد الأدنى لفرع الأخطار لمن لا يخضع للمعاشات 400 ريال وفق القواعد الحالية.'],['نطاقات 2026','الحاسبة العامة لنطاقات المطور مخصصة للكيانات ذات 6 عاملين فأكثر، والمنشآت الأصغر لها معالجة مستقلة.']
];
const PRACTICE=[
'عند تعارض سجل الحضور مع تكليف ميداني موثق يجب التحقق من مصدر البيانات قبل اعتبار اليوم غيابا.',
'التحقيق التأديبي يبدأ بتثبيت الواقعة والدليل وتمكين العامل من الرد قبل اختيار الجزاء.',
'عدم التجديد في عقد يتجدد تلقائيا يحتاج مراجعة مهلة الإشعار التعاقدية وإثبات التبليغ.',
'خطأ الرواتب يعالج بعد التحقق والتواصل وتطبيق ضوابط الخصم أو الاسترداد، لا بخصم عشوائي.',
'قرار التوظيف الأفضل يوثق معايير موحدة وأدلة مقابلة بدلا من الانطباع العام.',
'فترة التهيئة تشمل الصلاحيات والأدوات والسياسات وخطة 30/60/90 وليس توقيع العقد فقط.'
];
function key(){return process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY||process.env.GOOGLE_GENERATIVE_AI_API_KEY||''}
function seedNum(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed||1;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296)}
function fallback(count,seed){const r=rng(seedNum(seed)),out=[];const all=[...RULES.map((x,i)=>({id:'r'+i,ref:x[0],fact:x[1],g:'نظام العمل والامتثال'})),...PRACTICE.map((x,i)=>({id:'p'+i,ref:'ممارسة HR',fact:x,g:'ممارسة HR'}))];for(let n=0;n<count;n++){const x=all[Math.floor(r()*all.length)],style=n%3,wrong=['لا توجد قاعدة ثابتة ويترك الأمر للمدير','يطبق الإجراء مباشرة دون تحقق أو توثيق','تستخدم القاعدة الأعلى دائما دون النظر لنوع الحالة'];let q,a,c;if(style===0){q='أي عبارة أدق مهنيا ونظاميا؟';a=[x.fact,...wrong];c=0}else if(style===1){q='صح أم خطأ: '+x.fact;a=['صح','خطأ'];c=0}else{q='في حالة عملية، ما التصرف الذي يعكس هذه القاعدة: '+x.ref+'؟';a=['التحقق من الوقائع والمستندات ثم تطبيق القاعدة ذات الصلة','تطبيق الجزاء الأعلى مباشرة','تجاهل نص العقد','الاعتماد على رأي شفهي فقط'];c=0}const rot=Math.floor(r()*a.length);a=[...a.slice(rot),...a.slice(0,rot)];c=(c-rot+a.length)%a.length;out.push({id:`daily-${seed}-${x.id}-${n}`,g:x.g,q,a,c,e:x.fact,r:x.ref})}return out}
function extractJSON(text){const m=String(text||'').match(/\[[\s\S]*\]/);if(!m)return null;try{return JSON.parse(m[0])}catch{return null}}
function valid(q){return q&&typeof q.q==='string'&&Array.isArray(q.a)&&q.a.length===4&&Number.isInteger(q.c)&&q.c>=0&&q.c<4&&typeof q.e==='string'&&typeof q.r==='string'}
export default async function handler(req,res){try{const count=Math.max(1,Math.min(15,Number(req.method==='POST'?req.body?.count:req.query?.count)||10)),seed=String((req.method==='POST'?req.body?.seed:req.query?.seed)||new Date().toISOString().slice(0,10));const apiKey=key();if(!apiKey)return res.status(200).json({ok:true,mode:'daily-local',questions:fallback(count,seed),updatedAt:new Date().toISOString()});const exclude=Array.isArray(req.body?.exclude)?req.body.exclude.slice(0,100):[];const ai=new GoogleGenAI({apiKey});const context=RULES.map(x=>`${x[0]}: ${x[1]}`).join('\n');const prompt=`أنشئ ${count} أسئلة عربية أصلية لاختبار أخصائي موارد بشرية سعودي.\nلا تخترع أي مادة أو رقم أو قاعدة. استخدم فقط السياق أدناه. اجعل أغلب الأسئلة حالات قصيرة تتطلب اختيار الإجراء الصحيح، وليس حفظ أرقام فقط. كل سؤال 4 خيارات وإجابة صحيحة واحدة وشرح مختصر ومرجع. تجنب أي صياغة مطابقة للمعرفات السابقة: ${exclude.join(', ')}.\nأعد JSON array فقط بالشكل: [{"id":"unique","g":"الفئة","q":"السؤال","a":["1","2","3","4"],"c":0,"e":"الشرح","r":"المرجع"}].\nالسياق:\n${context}\nممارسات إضافية:\n${PRACTICE.join('\n')}`;const out=await ai.models.generateContent({model:'gemini-2.5-flash',contents:prompt});const arr=extractJSON(out?.text||'')?.filter(valid).slice(0,count)||[];if(arr.length<count){const more=fallback(count-arr.length,seed+'-fallback');arr.push(...more)}res.status(200).json({ok:true,mode:'ai-refresh',questions:arr,updatedAt:new Date().toISOString()})}catch(e){const count=Math.max(1,Math.min(15,Number(req.body?.count)||10));res.status(200).json({ok:true,mode:'daily-local',questions:fallback(count,new Date().toISOString().slice(0,10)+'-error'),updatedAt:new Date().toISOString(),warning:'تم استخدام التحديث المحلي لأن مولد AI لم يستجب.'})}}